-- =====================================================================
-- L2 (gold) — ANALYTICS: spend fact + Spend Intelligence enrichment
-- DT_SPEND_360 (PO spend) plus DT_SUPPLIER_RISK, DT_CATEGORY_HIERARCHY,
-- DT_SAVINGS_OPPORTUNITY, DT_INVOICE_SPEND (risk, ESG, taxonomy, savings,
-- non-PO spend). Note: enrichment tables carry representative demo values.
-- =====================================================================

create or replace schema SAP_SPEND_360.ANALYTICS;

create or replace TABLE SAP_SPEND_360.ANALYTICS.DT_CATEGORY_HIERARCHY (
	CATEGORY VARCHAR(24),
	CATEGORY_CODE VARCHAR(256),
	L1_CATEGORY VARCHAR(8),
	L2_CATEGORY VARCHAR(23),
	L3_CATEGORY VARCHAR(24),
	IS_ADDRESSABLE BOOLEAN,
	BENCHMARK_INDEX NUMBER(3,0),
	CATEGORY_SPEND NUMBER(38,0)
);
create or replace TABLE SAP_SPEND_360.ANALYTICS.DT_INVOICE_SPEND (
	INVOICE_ID VARCHAR(16777216),
	SUPPLIER VARCHAR(256),
	CATEGORY VARCHAR(24),
	COMPANY VARCHAR(16),
	SPEND_TYPE VARCHAR(16777216),
	INVOICE_DATE DATE,
	SPEND NUMBER(6,0),
	IS_MAVERICK BOOLEAN,
	PPV_AMOUNT NUMBER(4,0)
);
create or replace TABLE SAP_SPEND_360.ANALYTICS.DT_SAVINGS_OPPORTUNITY (
	OPP_ID VARCHAR(16777216),
	CATEGORY VARCHAR(24),
	SUPPLIER VARCHAR(256),
	OPP_TYPE VARCHAR(26),
	ESTIMATED_SAVINGS NUMBER(38,0),
	SAVINGS_PCT NUMBER(7,1),
	STATUS VARCHAR(16777216),
	OWNER VARCHAR(16777216),
	TARGET_DATE DATE
);
create or replace dynamic table SAP_SPEND_360.ANALYTICS.DT_SPEND_360(
	PO_ID,
	PO_ITEM,
	SUPPLIER,
	CATEGORY_CODE,
	CATEGORY,
	COMPANY,
	CURRENCY,
	PLANT,
	PURCHASING_GROUP,
	PURCHASING_ORG,
	BUYER,
	PO_DATE,
	PO_YEAR,
	PO_MONTH,
	ORDER_QUANTITY,
	NET_PRICE,
	SPEND,
	IS_ON_CONTRACT,
	CONTRACT_ID,
	ACCOUNT_ASSIGNMENT,
	IS_INVOICED,
	IS_DELIVERED
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
  PURCHASEORDER AS PO_ID, PURCHASEORDERITEM AS PO_ITEM, SUPPLIER,
  MATERIALGROUP AS CATEGORY_CODE,
  DECODE(MATERIALGROUP,'MG10','IT Hardware','MG11','Software & Licenses','MG20','Professional Services',
    'MG21','Consulting','MG30','Facilities & Real Estate','MG31','Utilities','MG40','Logistics & Freight',
    'MG41','Travel & Expense','MG50','Raw Materials','MG51','Packaging','MG60','MRO & Supplies',
    'MG61','Marketing & Advertising','MG70','Fleet & Equipment','MG80','Telecom','MG90','HR & Staffing','Other') AS CATEGORY,
  DECODE(COMPANYCODE,'1000','US Operations','2100','EU Operations','5000','Japan Operations','Other') AS COMPANY,
  DOCUMENTCURRENCY AS CURRENCY, PLANT, PURCHASINGGROUP AS PURCHASING_GROUP,
  PURCHASINGORGANIZATION AS PURCHASING_ORG, CREATEDBYUSER AS BUYER,
  PURCHASEORDERDATE AS PO_DATE, YEAR(PURCHASEORDERDATE) AS PO_YEAR,
  TO_CHAR(PURCHASEORDERDATE,'YYYY-MM') AS PO_MONTH,
  ORDERQUANTITY AS ORDER_QUANTITY, NETPRICEAMOUNT AS NET_PRICE, NETAMOUNT AS SPEND,
  IFF(PURCHASECONTRACT<>'',TRUE,FALSE) AS IS_ON_CONTRACT, PURCHASECONTRACT AS CONTRACT_ID,
  ACCOUNTASSIGNMENTCATEGORY AS ACCOUNT_ASSIGNMENT,
  ISFINALLYINVOICED AS IS_INVOICED, ISCOMPLETELYDELIVERED AS IS_DELIVERED
FROM SAP_SPEND_360.SAP_BDC_L1.PURCHASE_ORDER_ITEM;
create or replace TABLE SAP_SPEND_360.ANALYTICS.DT_SUPPLIER_RISK (
	SUPPLIER VARCHAR(256),
	SUPPLIER_NAME VARCHAR(265),
	PARENT_SUPPLIER VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	REGION VARCHAR(16777216),
	TIER VARCHAR(9),
	RISK_SCORE NUMBER(19,0),
	FINANCIAL_RISK NUMBER(25,6),
	GEO_RISK NUMBER(25,6),
	COMPLIANCE_RISK NUMBER(25,6),
	IS_SINGLE_SOURCE BOOLEAN,
	ESG_SCORE NUMBER(26,6),
	ENV_SCORE NUMBER(26,6),
	SOCIAL_SCORE NUMBER(26,6),
	GOV_SCORE NUMBER(26,6),
	IS_SUSTAINABLE BOOLEAN,
	IS_DIVERSE BOOLEAN,
	DIVERSITY_CLASS VARCHAR(16777216),
	PRIMARY_CATEGORY VARCHAR(24),
	ANNUAL_SPEND NUMBER(38,0),
	SUPPLIER_SINCE DATE
);
